[package]
name = "branchy"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "branchy"

[dependencies]
thiserror = "1.0.20"

hdk = { workspace = true }

serde = { workspace = true }

branchy_integrity = { workspace = true } 
